### ISSUE TITLE
ARM support for Docker images?

### ISSUE THREAD

**Issue by sokulski** [barbequesauce/Watcher3#144]
As best I can tell, the current Docker image for Watcher3 can't run on a RaspberryPi. When I try to load it (via OMV) on a Pi, the container reboots continuously with the following error:

`standard_init_linux.go:211: exec user process caused “exec format error`

It'd be great if this image could be compatible with multiple architectures, similar to how the ones from linuxserver.io work.

**Comment by barbequesauce** [comment]
Huh. Didn’t see this coming. @ellnic thoughts? Is it the alpine base or the apks?

**Comment by ellnic** [comment]
Yeah this is the expected behaviour because the image is amd64. It would need to be altered to support arm. It’s on the todo list but I just haven’t got round to it yet. Leave this issue open and I’ll sort it ASAP.

**Comment by ellnic** [comment]
@sokulski please can you pull ellnic/watcher3 and tell me if:

1. It pulls the correct arch for the Pi (most probably armhf unless you're running the modified kernel)
2. It works! :)

**Comment by barbequesauce** [comment]
i have both pi3b+'s and pi4b's, both present as armv7l and 32-bit under Raspbian Jessie & Buster - no arm64 here, sorry...

**Comment by ellnic** [comment]
Ok, no worries. Do you have docker on any of those? Does this pull/run ok? 

I have got a feeling it won't because of the manifest file. The manifest is just that, a manifest of different versions or arch's that allows you to just pull `ellnic/watcher3` and it grabs what you need. So you add tags like `amd64`, `armhf` and `arm64` to your autobuilds, then generate a manifest and push it to `latest` and when the user pulls just `ellnic/watcher3`, it just works. The problem being that I think this needs to be generated each time a change occurs as it uses hashes not just tags. So if a single tiny commit happens, it will break. Seems like a massive oversight to me, there is no manifest control in the hub, but maybe this is on the roadmap.

The easiest solution I can see right now is to separate off the arch's as tags. So instead of:

`docker pull ellnic/watcher3` automatically grabbing the right arch, we have that for amd64 and something like:

`docker pull ellnic/watcher3:arm64` and `docker pull ellnic/watcher3:armhf` for arm. 

No real issue as we can just put it in the readme. If we do it like this it'll be a set and forget again.

**Comment by sokulski** [comment]
@ellnic 

> 1. It pulls the correct arch for the Pi (most probably armhf unless you're running the modified kernel)
I'm not sure how to verify that. When I `docker inspect image` on this image, architecture says amd64. But...

> 2. It works! :)
Yes, it does work. Booted up just fine, web-ui loaded and functionality all seems to be there.

The only thing out of the ordinary is an alert message in the bottom right:
`Error Checking for Updates 
Current local hash not in git history.`

Beyond that, all works as expected!

**Comment by ellnic** [comment]
That's great! I am utterly surprised it's working... I thought that once a change was made and the hashes changed, the manifest would stop working. Just bear in mind that if we merge changes to barbequeauce's master and for some reason down the line it stops pulling/running correctly, you will need to specify a tag ie. `barbequesauce/watcher3:armhf`. We'll work out specifics and it'll be in the readme.

That error is to be expected it's because the link in the code points to barbequesauce, but it's building from mine. It will resolve once you move to barbequesauce and the hashes match again. 

I'll post again here when barbequesauce's master is ready, then all you have to do is change the docker repo name :)

**Comment by ellnic** [comment]
Ok, spoke too soon, just checked the hashes and the manifest links to images built 8 hours ago still, so even though the manifest works, you have an old image. So I was right, any little change will require the repo owner to push a new manifest each time... urgh. I don't get why they can't just automate this.

So, very soon you'll need to use something like `barbequesauce/watcher3:armhf`

**Comment by barbequesauce** [comment]
Kick them tires and let's see how she rolls...

**Comment by barbequesauce** [comment]
@ellnic don't forget the readme.md fixes please :) I think a bunch of badges need to be tweaked as well as that big bold block

**Comment by ellnic** [comment]
Done! :-)

**Comment by ellnic** [comment]
@sokulski so everythings looking good this morning. You should change to using `barbequesauce/watcher3:armhf` now.

**Comment by sokulski** [comment]
@ellnic Thanks! Pardon my ignorance, but how do I change the repo that is being used for updates?

**Comment by ellnic** [comment]
@sokulski if you mean the error you mentioned above about hashes not in history, you don’t need to do anything. It will resolve once you switch to barbequesauce’s repo. When you pull my docker it still contains the link to barbequesauce’s repo (changing this would be tiresome to maintain and I PR anything worthwhile anyway) but once you switch to running the barbequesauce docker it will go away. It doesn’t really apply to docker anyway as you update through docker. It’s for people who pull the git and run that way.

**Comment by sokulski** [comment]
@ellnic Gotcha. So I should make a new container using barbequesauce's repo?

**Comment by ellnic** [comment]
@sokulski Yes, that's right. I haven't used OMV in a while, and I only ever used docker from CLI but as an example:

```
docker run -d \
  --name=watcher3 \
  -v /path/to/config/:/config \
  -v /path/to/downloads/:/downloads \
  -v /path/to/movies/:/movies \
  -e UMASK_SET=022 \
  -e APP_UID=1000 -e APP_GID=1000 \
  -p 9090:9090 \
  ellnic/watcher3
```

would become:

```
docker run -d \
  --name=watcher3 \
  -v /path/to/config/:/config \
  -v /path/to/downloads/:/downloads \
  -v /path/to/movies/:/movies \
  -e UMASK_SET=022 \
  -e APP_UID=1000 -e APP_GID=1000 \
  -p 9090:9090 \
  barbequesauce/watcher3:armhf
```
Just change **ellnic/watcher3** to **barbequesauce/watcher3:armhf** to pull the correct image for the Pi. Settings will be preserved because of your config dir, it should just work. Then there's probably an update button in the OMV GUI to keep it up to date - I looked at a German screenshot and I think that says 'Aktualisieren' at the end (update), or you can:

1. Stop container
2. Delete container
3. Pull barbequesauce/watcher3:armhf again
4. Run with above command

**Comment by ellnic** [comment]
@sokulski I found an issue this morning to do with build context and me having moved the (now many) docker specific files into the `Docker` sub dir. I believe I have now fixed this (sorry, totally my fault).

Can you tell me if you can pull and run `barbequesauce/watcher3:armhf`? I have tested on an amd64 machine and it now works as expected - this shouldn't differ across archs but please let me know :)

**Comment by sokulski** [comment]
@ellnic So sorry for the delay in finding time to verify this.

I've been successful running `barbequesauce/watcher3:armhf` and I was able to perform an update shortly after booting.

Thank you for your assistance, and if I can be of use with any further testing let me know.

**Comment by ellnic** [comment]
@sokulski no worries, I haven’t been too quick to respond lately either. Glad it’s all sorted for you now. You shouldn’t have any more issues.
